const API="/.netlify/functions";let sb;
async function config(){const r=await fetch(`${API}/public-config`);const d=await r.json();sb=window.supabase.createClient(d.supabaseUrl,d.supabaseAnonKey)}
async function init(){try{await config();const {data:{session}}=await sb.auth.getSession();if(session)showDash(session);document.querySelector("#login-form").addEventListener("submit",login);document.querySelector("#logout").onclick=async()=>{await sb.auth.signOut();location.reload()};document.querySelector("#refresh").onclick=load;document.querySelector("#banner-form").addEventListener("submit",saveBanner);document.querySelector("#code-form").addEventListener("submit",generate)}catch(e){document.querySelector("#login-status").textContent=e.message}}
async function login(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),st=document.querySelector("#login-status");st.textContent="Signing in…";const {data,error}=await sb.auth.signInWithPassword({email:f.email,password:f.password});if(error){st.textContent=error.message;return}const r=await fetch(`${API}/admin-me`,{headers:{Authorization:`Bearer ${data.session.access_token}`}});if(!r.ok){await sb.auth.signOut();st.textContent="This account is not authorised as the academy admin.";return}showDash(data.session)}
async function showDash(session){document.querySelector("#login-view").hidden=true;document.querySelector("#dashboard").hidden=false;document.querySelector("#admin-user").textContent=`Signed in as ${session.user.email}`;await load()}
async function load(){const {data:{session}}=await sb.auth.getSession();if(!session)return;const r=await fetch(`${API}/admin-data`,{headers:{Authorization:`Bearer ${session.access_token}`}});const d=await r.json();if(!r.ok){alert(d.message||"Could not load admin data");return}document.querySelector("#students-count").textContent=d.students.length;document.querySelector("#inquiries-count").textContent=d.inquiries.length;document.querySelector("#payments-count").textContent=d.payments.length;document.querySelector("#codes-count").textContent=d.codes.length;await loadBanner();document.querySelector("#records").innerHTML=`<h3>Students</h3>${table(d.students,["child_name","parent_name","email","level","created_at"])}<h3>Inquiries</h3>${table(d.inquiries,["parent_name","email","topic","message","created_at"])}<h3>Payments</h3>${table(d.payments,["email","plan","amount","status","reference","created_at"])}<h3>VIP codes</h3>${table(d.codes,["code","plan","days","used","created_at"])}`}
function table(rows,keys){if(!rows.length)return"<p>No records yet.</p>";return`<table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr>${keys.map(k=>`<th style="text-align:left;border-bottom:1px solid #ddd;padding:8px">${k}</th>`).join("")}</tr></thead><tbody>${rows.slice(0,50).map(r=>`<tr>${keys.map(k=>`<td style="border-bottom:1px solid #eee;padding:8px">${String(r[k]??"").slice(0,180)}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
async function generate(e){e.preventDefault();const {data:{session}}=await sb.auth.getSession(),f=Object.fromEntries(new FormData(e.target)),st=document.querySelector("#code-result");const r=await fetch(`${API}/admin-code`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(f)});const d=await r.json();st.textContent=d.message||d.code||"Done";if(r.ok)load()}
init();
async function loadBanner(){const r=await fetch(`${API}/site-settings`);const d=await r.json();if(!r.ok)return;const f=document.querySelector("#banner-form");if(!f)return;for(const [k,v] of Object.entries(d.settings||{})){if(f.elements[k])f.elements[k].value=v}}
async function saveBanner(e){e.preventDefault();const {data:{session}}=await sb.auth.getSession(),f=Object.fromEntries(new FormData(e.target)),st=document.querySelector("#banner-status");st.textContent="Saving…";const r=await fetch(`${API}/site-settings`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(f)});const d=await r.json();st.textContent=d.message||"Saved";if(r.ok)loadBanner()}
