window.EXAM_BANK = [
  {"subject":"Mathematics","q":"Solve 3x - 7 = 11.","a":["x = 4","x = 5","x = 6","x = 7"],"c":1},
  {"subject":"Mathematics","q":"If log10(1000) = y, find y.","a":["2","3","10","100"],"c":1},
  {"subject":"Mathematics","q":"Simplify 2^3 × 2^4.","a":["2^7","4^7","2^12","8^4"],"c":0},
  {"subject":"Mathematics","q":"Find the 10th term of the arithmetic progression 4, 7, 10, …","a":["28","31","34","37"],"c":1},
  {"subject":"Mathematics","q":"Find the common ratio of the geometric progression 3, 6, 12, 24, …","a":["1","2","3","6"],"c":1},
  {"subject":"Mathematics","q":"If A = [[2,1],[3,4]], find det(A).","a":["5","8","11","−5"],"c":0},
  {"subject":"Mathematics","q":"Find the inverse of the 1×1 matrix [5].","a":["[−5]","[1/5]","[5]","[0]"],"c":1},
  {"subject":"Mathematics","q":"A circle has radius 7 cm. Using π = 22/7, find its circumference.","a":["22 cm","44 cm","49 cm","154 cm"],"c":1},
  {"subject":"Mathematics","q":"The angle subtended by an arc at the centre is 96°. What angle does the same arc subtend at the circumference?","a":["24°","48°","96°","192°"],"c":1},
  {"subject":"Mathematics","q":"A bag contains 5 red and 3 blue balls. What is the probability of selecting a blue ball at random?","a":["3/5","3/8","5/8","1/3"],"c":1},
  {"subject":"Mathematics","q":"If P(A)=0.4, P(B)=0.5 and A and B are independent, find P(A∩B).","a":["0.1","0.2","0.4","0.9"],"c":1},
  {"subject":"Mathematics","q":"Find the gradient of the line joining (2,3) and (6,11).","a":["1","2","3","4"],"c":1},
  {"subject":"Mathematics","q":"Differentiate y = x^3 − 4x with respect to x.","a":["3x^2 − 4","x^2 − 4","3x − 4","x^3 − 4"],"c":0},
  {"subject":"Mathematics","q":"Evaluate ∫ 2x dx.","a":["x^2 + C","2x^2 + C","x + C","2 + C"],"c":0},
  {"subject":"Mathematics","q":"If sin θ = 3/5 for an acute angle θ, find cos θ.","a":["3/5","4/5","5/3","1/5"],"c":1},
  {"subject":"Mathematics","q":"Solve 2x + y = 9 and x − y = 3.","a":["x=2,y=5","x=3,y=3","x=4,y=1","x=5,y=−1"],"c":2},
  {"subject":"Mathematics","q":"The mean of 6, 8, 10, 12 and x is 10. Find x.","a":["12","14","16","18"],"c":1},
  {"subject":"English","q":"Choose the word that best completes: “If I ___ earlier, I would have met the principal.”","a":["arrive","arrived","had arrived","have arrived"],"c":2},
  {"subject":"English","q":"Identify the subordinate clause: “Although it was raining, the players continued the match.”","a":["the players","continued the match","Although it was raining","the match"],"c":2},
  {"subject":"English","q":"Choose the correctly punctuated sentence.","a":["The teacher said “work hard”.","The teacher said, “Work hard.”","The teacher said “Work hard”.","The teacher, said “work hard.”"],"c":1},
  {"subject":"English","q":"Select the option with the correct concord: “Neither the boys nor the girl ___ responsible.”","a":["are","were","is","have"],"c":2},
  {"subject":"English","q":"What figure of speech is used in “The wind whispered through the trees”?","a":["Simile","Personification","Oxymoron","Pun"],"c":1},
  {"subject":"English","q":"Choose the closest meaning to “meticulous”.","a":["Careless","Very careful","Angry","Confused"],"c":1},
  {"subject":"English","q":"Choose the word opposite in meaning to “scarce”.","a":["Rare","Limited","Abundant","Small"],"c":2},
  {"subject":"English","q":"Change to indirect speech: Ada said, “I will return tomorrow.”","a":["Ada said that she would return the next day.","Ada said that I will return tomorrow.","Ada says she returned tomorrow.","Ada said she will return yesterday."],"c":0},
  {"subject":"English","q":"Change to passive voice: “The committee approved the proposal.”","a":["The proposal approved the committee.","The proposal was approved by the committee.","The committee was approved by the proposal.","The proposal has approving the committee."],"c":1},
  {"subject":"English","q":"Which word functions as an adverb in “She spoke confidently to the audience”?","a":["She","spoke","confidently","audience"],"c":2},
  {"subject":"English","q":"Choose the correctly spelt word.","a":["Accomodation","Accommodation","Acommodation","Accommmodation"],"c":1},
  {"subject":"English","q":"In an argumentative essay, the thesis statement mainly presents the writer’s ___.","a":["address","central position","greeting","bibliography"],"c":1},
  {"subject":"English","q":"Which option is an example of a rhetorical question?","a":["Where are you going?","Who would deliberately destroy a good opportunity?","Please close the door.","The meeting begins at noon."],"c":1},
  {"subject":"English","q":"Choose the correct preposition: “She has been absent ___ Monday.”","a":["for","since","at","by"],"c":1},
  {"subject":"English","q":"What is the main purpose of a summary?","a":["To reproduce every sentence","To present the essential ideas concisely","To add unrelated opinions","To increase the length of a passage"],"c":1},
  {"subject":"English","q":"Which register is most appropriate in a legal document?","a":["Recipe ingredients","Plaintiff and defendant","Goalkeeper and striker","Crop rotation"],"c":1},
  {"subject":"English","q":"Select the sentence with correct parallel structure.","a":["She likes reading, to swim and cycling.","She likes reading, swimming and cycling.","She likes to read, swimming and cycle.","She likes reading, to swim and to cycling."],"c":1},
  {"subject":"Physics","q":"A body moves with uniform velocity of 15 m/s for 8 s. Find the distance travelled.","a":["23 m","120 m","150 m","1.875 m"],"c":1},
  {"subject":"Physics","q":"A force of 20 N acts on a mass of 5 kg. Find the acceleration.","a":["0.25 m/s²","4 m/s²","15 m/s²","100 m/s²"],"c":1},
  {"subject":"Physics","q":"A 2 kg object is raised through 5 m. Take g = 10 m/s². Find its gain in gravitational potential energy.","a":["10 J","25 J","100 J","250 J"],"c":2},
  {"subject":"Physics","q":"A machine does 600 J of work in 20 s. What is its power?","a":["30 W","120 W","580 W","12,000 W"],"c":0},
  {"subject":"Physics","q":"Which quantity is measured in coulombs?","a":["Current","Charge","Resistance","Power"],"c":1},
  {"subject":"Physics","q":"Two resistors of 4 Ω and 6 Ω are connected in series. Find the total resistance.","a":["2 Ω","10 Ω","24 Ω","1.5 Ω"],"c":1},
  {"subject":"Physics","q":"For resistors connected in parallel, the effective resistance is generally ___ the smallest individual resistance.","a":["greater than","equal to twice","less than","unrelated to"],"c":2},
  {"subject":"Physics","q":"A transformer has 200 turns in the primary coil and 1000 turns in the secondary. If the primary voltage is 20 V, find the secondary voltage for an ideal transformer.","a":["4 V","40 V","100 V","200 V"],"c":2},
  {"subject":"Physics","q":"Which phenomenon demonstrates the wave nature of light most directly?","a":["Photoelectric effect","Interference","Thermionic emission","Radioactivity"],"c":1},
  {"subject":"Physics","q":"The frequency of a wave is 50 Hz and its wavelength is 4 m. Find its speed.","a":["12.5 m/s","46 m/s","54 m/s","200 m/s"],"c":3},
  {"subject":"Physics","q":"A projectile is launched horizontally from a height. Ignoring air resistance, its horizontal acceleration is ___.","a":["g","zero","greater than g","dependent on mass"],"c":1},
  {"subject":"Physics","q":"In simple harmonic motion, acceleration is directed ___ the displacement from the equilibrium position.","a":["in the same direction as","opposite to","perpendicular to","randomly to"],"c":1},
  {"subject":"Physics","q":"The half-life of a radioactive substance is 4 hours. What fraction remains after 12 hours?","a":["1/2","1/4","1/8","1/16"],"c":2},
  {"subject":"Physics","q":"Which radiation has the greatest penetrating power among alpha, beta and gamma?","a":["Alpha","Beta","Gamma","They are equal"],"c":2},
  {"subject":"Physics","q":"A wire carries 3 A through a potential difference of 12 V. Find its resistance.","a":["0.25 Ω","4 Ω","9 Ω","36 Ω"],"c":1},
  {"subject":"Physics","q":"Which device converts mechanical energy directly into electrical energy?","a":["Electric motor","Generator","Transformer","Capacitor"],"c":1},
  {"subject":"Chemistry","q":"How many moles are present in 18 g of water, H2O? (H=1, O=16)","a":["0.5 mol","1 mol","2 mol","18 mol"],"c":1},
  {"subject":"Chemistry","q":"What volume does 0.5 mol of a gas occupy at STP if 1 mol occupies 22.4 dm³?","a":["11.2 dm³","22.4 dm³","44.8 dm³","5.6 dm³"],"c":0},
  {"subject":"Chemistry","q":"Which factor does NOT normally affect the rate of a reaction?","a":["Temperature","Concentration","Catalyst","Colour of the reaction vessel"],"c":3},
  {"subject":"Chemistry","q":"A catalyst increases reaction rate mainly by ___.","a":["increasing the equilibrium constant","lowering activation energy","increasing product mass","raising the final temperature"],"c":1},
  {"subject":"Chemistry","q":"For an exothermic equilibrium, increasing temperature generally shifts equilibrium toward the ___.","a":["products","reactants","catalyst","solvent only"],"c":1},
  {"subject":"Chemistry","q":"During electrolysis of molten sodium chloride, sodium ions are discharged at the ___.","a":["anode","cathode","salt bridge","electrolyte surface"],"c":1},
  {"subject":"Chemistry","q":"Oxidation is best described in electron terms as ___.","a":["gain of electrons","loss of electrons","gain of neutrons","loss of protons only"],"c":1},
  {"subject":"Chemistry","q":"Which organic compound contains the functional group −OH?","a":["Alkene","Alcohol","Alkane","Aldehyde only"],"c":1},
  {"subject":"Chemistry","q":"What is the general formula of alkenes?","a":["CnH2n+2","CnH2n","CnH2n−2","CnHn"],"c":1},
  {"subject":"Chemistry","q":"Ethene reacts with bromine water by an addition reaction. What is the observation?","a":["Blue solution becomes red","Orange/brown bromine colour is decolourised","Gas becomes green","A white precipitate forms"],"c":1},
  {"subject":"Chemistry","q":"Which homologous series contains the compound CH3COOH?","a":["Alkanes","Alkenes","Alkanoic acids","Alkynes"],"c":2},
  {"subject":"Chemistry","q":"A solution with pH 7 at 25°C is ___.","a":["strongly acidic","neutral","strongly alkaline","a buffer necessarily"],"c":1},
  {"subject":"Chemistry","q":"Which salt is formed when hydrochloric acid reacts completely with sodium hydroxide?","a":["NaCl","Na2CO3","NaOH","H2SO4"],"c":0},
  {"subject":"Chemistry","q":"What is the oxidation state of sulfur in H2SO4?","a":["+2","+4","+6","−2"],"c":2},
  {"subject":"Chemistry","q":"If 2 mol H2 reacts completely with 1 mol O2, how many moles of H2O are formed?","a":["1 mol","2 mol","3 mol","4 mol"],"c":1},
  {"subject":"Chemistry","q":"What is the purpose of a salt bridge in an electrochemical cell?","a":["To increase the electrode mass","To maintain electrical neutrality by ion movement","To stop electron flow","To provide the external wire"],"c":1},
  {"subject":"Government","q":"A major feature of federalism is the constitutional allocation of powers between the ___.","a":["levels of government","private companies","media houses","traditional markets"],"c":0},
  {"subject":"Government","q":"Which institution normally interprets the constitution in a constitutional dispute?","a":["Judiciary","Cabinet only","Political party","Civil service union"],"c":0},
  {"subject":"Government","q":"A bicameral legislature consists of ___.","a":["one chamber","two chambers","three chambers","no chamber"],"c":1},
  {"subject":"Government","q":"A political party manifesto mainly states the party’s ___.","a":["policies and programme","court judgments","school timetable","military orders"],"c":0},
  {"subject":"Government","q":"An electoral system based on the candidate with the highest number of votes winning a constituency is commonly called ___.","a":["first-past-the-post","proportional representation","lottery voting","consensus appointment"],"c":0},
  {"subject":"Government","q":"Proportional representation is designed to allocate seats broadly in proportion to ___.","a":["population alone","votes received","land area","age of candidates"],"c":1},
  {"subject":"Government","q":"A public corporation is established mainly to provide services considered important to the ___.","a":["public interest","private household only","foreign embassies only","political party headquarters"],"c":0},
  {"subject":"Government","q":"One common source of finance for a public corporation is ___.","a":["government funding","exam answers","private votes","court sentences"],"c":0},
  {"subject":"Government","q":"The principle of checks and balances is intended to ___.","a":["prevent concentration of power","abolish elections","remove courts","stop law-making"],"c":0},
  {"subject":"Government","q":"A pressure group differs from a political party because a pressure group primarily seeks to ___.","a":["influence public policy without necessarily seeking governmental office","conduct all elections","replace the constitution","appoint judges directly"],"c":0},
  {"subject":"Government","q":"A constitution that is difficult to amend through ordinary legislative procedures is described as ___.","a":["flexible","rigid","oral","temporary"],"c":1},
  {"subject":"Government","q":"Which of the following is a major function of the legislature?","a":["Law-making and oversight","Issuing passports only","Running private businesses","Marking examinations"],"c":0},
  {"subject":"Government","q":"A referendum is a process in which citizens ___.","a":["vote directly on a specific proposal","appoint every civil servant","choose court sentences","write the national budget individually"],"c":0},
  {"subject":"Government","q":"Pre-colonial political administration in many Hausa-Fulani emirates was characterised by ___.","a":["an emirate system with hierarchical offices","a modern federal senate","universal suffrage","a presidential cabinet"],"c":0},
  {"subject":"Government","q":"The traditional Yoruba political system in many areas included the institution of the ___.","a":["Oba","Emir only","Governor-General","Prime Minister"],"c":0},
  {"subject":"Government","q":"One important advantage claimed for local government is that it ___.","a":["brings administration closer to local communities","abolishes state government","removes citizen participation","ends traditional institutions"],"c":0},
  {"subject":"Government","q":"Political socialisation refers to the process by which people acquire ___.","a":["political values and attitudes","only mathematical skills","weather information","medical prescriptions"],"c":0},
  {"subject":"Biology","q":"During mitosis, sister chromatids separate during ___.","a":["prophase","metaphase","anaphase","interphase"],"c":2},
  {"subject":"Biology","q":"Meiosis is important because it produces cells with ___.","a":["the same chromosome number only","half the usual chromosome number","double the chromosome number","no chromosomes"],"c":1},
  {"subject":"Biology","q":"Crossing over occurs during ___.","a":["prophase I of meiosis","prophase of mitosis only","telophase II","cytokinesis"],"c":0},
  {"subject":"Biology","q":"Which process converts atmospheric nitrogen into compounds plants can use through microorganisms?","a":["Nitrogen fixation","Transpiration","Photosynthesis","Germination"],"c":0},
  {"subject":"Biology","q":"Nitrifying bacteria convert ammonia compounds into ___.","a":["nitrates/nitrites","glucose","proteins directly","oxygen"],"c":0},
  {"subject":"Biology","q":"Which tissue transports water and mineral salts upward in a plant?","a":["Phloem","Xylem","Epidermis","Cambium only"],"c":1},
  {"subject":"Biology","q":"Translocation of manufactured food in plants occurs mainly through the ___.","a":["xylem","phloem","stomata","root cap"],"c":1},
  {"subject":"Biology","q":"The opening and closing of stomata are controlled by ___.","a":["guard cells","root hairs","xylem vessels","pollen grains"],"c":0},
  {"subject":"Biology","q":"A reflex action is coordinated rapidly through a ___.","a":["reflex arc","digestive tract","nephron only","vascular bundle"],"c":0},
  {"subject":"Biology","q":"The sensory neurone carries impulses from a receptor toward the ___.","a":["central nervous system","muscle only","skin surface","gland only"],"c":0},
  {"subject":"Biology","q":"Which part of the brain is chiefly associated with balance and coordination?","a":["Cerebrum","Cerebellum","Medulla only","Hypothalamus only"],"c":1},
  {"subject":"Biology","q":"Natural selection acts on heritable variation by favouring traits that improve ___.","a":["survival and reproduction","cell size only","mutation rate only","blood colour"],"c":0},
  {"subject":"Biology","q":"A population is best defined as organisms of the same species living in the same ___.","a":["area at the same time","kingdom only","cell","organ system"],"c":0},
  {"subject":"Biology","q":"In an ecosystem, decomposers are important because they ___.","a":["return nutrients to the environment","produce all sunlight","stop respiration","remove all oxygen"],"c":0},
  {"subject":"Biology","q":"The relationship in which both organisms benefit is called ___.","a":["parasitism","mutualism","predation","competition"],"c":1},
  {"subject":"Biology","q":"Which ecological pyramid is always upright?","a":["Pyramid of energy","Pyramid of numbers","Pyramid of biomass","None"],"c":0},
  {"subject":"Biology","q":"If a heterozygous tall plant Tt is crossed with a short plant tt, what proportion of offspring is expected to be short?","a":["0%","25%","50%","100%"],"c":2}
];