window.LESSON_CONTENT = {};
const L=(goal,explain,examples,practice,challenge)=>({goal,explain,examples,practice,challenge});
const add=(subject,items)=>{window.LESSON_CONTENT[subject]=Object.assign(window.LESSON_CONTENT[subject]||{},items)};

add("Colours",{"Exploring the Colour Red":L("Recognise red and connect it with familiar objects.","Red is a bright colour. We can find red in many safe, everyday objects. Look carefully at an object and compare its colour with red.",["🍎 An apple can be red.","❤️ A heart symbol is often shown in red."],["Find one red object near you.","Say: 'This is red.'"],"Name two more things that can be red.")});
add("Shapes",{"The Magic Circle":L("Recognise a circle and describe its smooth round edge.","A circle is a round 2D shape. It has no sharp corners or pointy sides. We see circles in wheels, plates and clocks.",["⚪ A coin is round.","⭕ A wheel has a circular shape."],["Trace a circle with your finger.","Find a circular object."],"Draw a large circle and colour it.")});
add("Numbers",{"Counting 1 to 3":L("Count three objects using one number for each object.","Counting tells us how many objects there are. Touch each object once while saying 1, 2, 3.",["🍎 = 1","🍎🍎 = 2","🍎🍎🍎 = 3"],["Clap three times while counting.","Count three toys."],"Put three objects in a row and count them without skipping any.")});
add("Phonics",{"Letter Sound S (/s/)":L("Hear, say and recognise the /s/ sound.","The letter S commonly represents the /s/ sound, like the sound a friendly snake makes. S begins words such as sun, sock and snake.",["S — sun ☀️","S — sock 🧦","S — snake 🐍"],["Say /s/ three times.","Find a word that begins with S."],"Make a short list of three S words.")});
add("Literacy",{"Word Building (CVC)":L("Blend three sounds to read simple CVC words.","CVC means consonant-vowel-consonant. Say each sound, then blend them smoothly. For example, /c/ /a/ /t/ becomes cat.",["c-a-t → cat","d-o-g → dog","s-u-n → sun"],["Blend /m/ /a/ /p/.","Build one CVC word with letter cards."],"Create two new CVC words and read them aloud.")});
add("Numeracy",{"Addition Basics (Adding 1 More)":L("Understand that adding one increases a number by one.","When we add 1 more object, the total becomes the next number. Start with the objects you have, then add one and count again.",["2 + 1 = 3","4 + 1 = 5"],["Draw two circles and add one more.","Say the next number after 6."],"Make an addition story for 5 + 1.")});
add("Life Skills",{"Personal Hygiene (Handwashing)":L("Explain why and how to wash hands properly.","Soap and running water help remove dirt and germs from our hands. Wash before eating and after using the toilet, coughing, sneezing or playing outside.",["Wet → soap → scrub → rinse → dry","Scrub palms, backs of hands and between fingers."],["Put the handwashing steps in order.","Show how long you would scrub your hands."],"Teach the five-step handwashing routine to a family member.")});
add("Alphabet Skills",{"Letter Order: A to B":L("Identify B as the letter immediately after A.","The alphabet follows a fixed order. A comes first and B comes next. Recognising order helps children read and spell.",["A → B → C","A comes before B."],["Say A, B, C.","Point to B after finding A."],"Continue the sequence A, B, __, __.")});
add("Shapes",{"Square and Its Four Equal Sides":L("Recognise a square and count its four equal sides.","A square is a 2D shape with four sides. All four sides are equal in length and it has four corners.",["⬜ A square has 4 sides.","A tile can look like a square."],["Trace a square.","Count its four sides and four corners."],"Draw a square and label its four sides.")});

add("English",{
  "Nouns":L("Identify nouns that name people, places, animals and things.","A noun is a naming word. It can name a person, place, animal or thing.",["teacher, school, dog, book"],["Circle the noun in 'The dog runs.'","Name five nouns."],"Write a sentence containing three nouns."),
  "Singular and Plural Nouns":L("Tell whether a noun names one or more than one.","A singular noun names one. A plural noun names more than one. Many regular plurals are formed by adding s or es.",["book → books","box → boxes","child → children"],["Change cat to its plural.","Write one singular and one plural noun."],"Find three irregular plurals."),
  "Pronouns":L("Use pronouns to replace repeated nouns.","Pronouns such as he, she, it, they, we and you can stand in for nouns so sentences do not sound repetitive.",["Ada is happy. She is smiling.","The boys ran. They were fast."],["Replace 'Tunde' with a suitable pronoun.","Write two sentences using pronouns."],"Rewrite a short paragraph using pronouns correctly."),
  "Punctuation":L("Use basic punctuation to make writing clear.","A full stop ends a statement, a question mark ends a question and a capital letter begins a sentence. Commas can separate items or parts of a sentence.",["What is your name?","I like rice, beans and fish."],["Add punctuation to one sentence.","Write a question with a question mark."],"Correct the punctuation in a four-sentence paragraph."),
  "Adjectives":L("Identify words that describe nouns.","Adjectives give information about nouns, such as colour, size, number or quality.",["a red ball","a tall tree","three books"],["Add an adjective to 'dog'.","Underline the adjective in 'The small bird flew.'"],"Write three sentences with different adjectives."),
  "Verbs":L("Recognise action and state verbs in sentences.","A verb tells what someone or something does or describes a state. Examples include run, write, think, is and have.",["The child runs.","The book is heavy."],["Find the verb in 'Birds fly.'","Act out three action verbs."],"Write five sentences using different verbs."),
  "Tenses":L("Use verb forms to show when an action happens.","Tense helps show time. The past describes something that happened, the present describes what happens now, and the future describes what will happen.",["I walked. / I walk. / I will walk."],["Change 'play' into a past-tense sentence.","Write one future-tense sentence."],"Write three sentences about the same action in three tenses."),
  "Reading Comprehension":L("Read a passage and answer using evidence.","Comprehension means understanding what a text says and using details from it. Read for the main idea, then return to the text for evidence.",["Who? asks about a person.","Why? asks for a reason."],["Read a short paragraph and state its main idea.","Find one supporting detail."],"Answer a 'why' question using evidence from a passage."),
  "Paragraph Writing":L("Write a focused paragraph with connected ideas.","A good paragraph usually has one main idea, supporting details and a closing sentence. Sentences should follow a sensible order.",["Topic sentence → details → closing sentence"],["Write a paragraph about your school.","Underline the main idea."],"Improve a paragraph by adding two useful details."),
  "Vocabulary":L("Build word knowledge and use new words correctly.","Vocabulary includes the words we understand and use. Learning synonyms, antonyms and context clues helps us choose accurate words.",["happy → joyful","early ↔ late"],["Give a synonym for big.","Use 'careful' in a sentence."],"Learn three new words and use each in a sentence.")
});

add("Mathematics",{
  "Place Value":L("Understand the value of a digit because of its position.","In a number such as 4,582, the 4 represents thousands, 5 hundreds, 8 tens and 2 ones.",["4,582 = 4 thousands + 5 hundreds + 8 tens + 2 ones"],["State the place value of 7 in 3,742.","Write 6,205 in expanded form."],"Create a five-digit number and explain every digit."),
  "Addition and Subtraction":L("Add and subtract whole numbers accurately.","Addition combines amounts. Subtraction finds what remains or the difference. Align place values before calculating.",["245 + 132 = 377","500 − 275 = 225"],["Solve 348 + 127.","Solve 700 − 286."],"Write a word problem that needs both operations."),
  "Multiplication and Division":L("Use equal groups and sharing to multiply and divide.","Multiplication finds the total in equal groups. Division shares a quantity into equal groups or asks how many groups fit.",["4 × 6 = 24","24 ÷ 6 = 4"],["Draw 3 groups of 5.","Share 20 objects among 4 groups."],"Explain how multiplication and division are related."),
  "Fractions":L("Understand fractions as equal parts of a whole.","A fraction has a numerator and denominator. The denominator shows how many equal parts make the whole; the numerator shows how many parts are selected.",["1/2 = one of two equal parts","3/4 = three of four equal parts"],["Shade 1/2 of a rectangle.","Find 3/4 of 8."],"Compare two simple fractions and explain your answer."),
  "Decimals":L("Read, compare and calculate with decimal numbers.","Decimals represent parts of a whole using place values such as tenths and hundredths.",["0.5 = 5 tenths","0.25 = 25 hundredths"],["Compare 0.4 and 0.35.","Add 1.2 + 0.7."],"Explain how 0.50 and 0.5 are related."),
  "Percentages":L("Understand percent as parts out of one hundred.","Percent means per hundred. 25% is 25 out of 100, or one quarter. Percentages are useful for discounts, comparisons and data.",["50% = 1/2","25% of 80 = 20"],["Find 10% of 90.","Find 25% of 40."],"Create a real-life percentage problem and solve it."),
  "Measurement":L("Measure length, mass, capacity and time using appropriate units.","Measurement compares a quantity with a standard unit. Choose units that match the size and type of quantity.",["metres for length","litres for capacity","kilograms for mass"],["Choose a suitable unit for a bottle of water.","Measure an object with a ruler."],"Explain why centimetres are useful for small lengths."),
  "Geometry":L("Recognise and describe common geometric shapes and properties.","Geometry studies shapes, space and their properties. We can describe shapes using sides, corners, angles and symmetry.",["triangle → 3 sides","rectangle → 4 sides"],["Name a shape with four sides.","Count the corners of a triangle."],"Compare a square and rectangle."),
  "Time and Money":L("Use clocks, calendars and money in everyday calculations.","Time helps us plan events, while money calculations involve recognising denominations, adding amounts and finding change.",["30 minutes = half an hour","₦1,000 − ₦350 = ₦650"],["Read a simple clock.","Calculate change from ₦2,000 after spending ₦750."],"Create a small shopping budget."),
  "Data Handling":L("Collect, organise and interpret simple data.","Data can be recorded in tables, tally charts and graphs. Look for totals, most common values and comparisons.",["A bar chart can compare favourite fruits.","A tally can count classroom choices."],["Make a tally of three colours.","Identify the largest value in a small chart."],"Create a five-item data question and answer it.")
});

add("Basic Science",{
  "States of Matter":L("Identify solids, liquids and gases and describe their properties.","Matter commonly exists as solid, liquid or gas. Solids keep their shape, liquids take the shape of their container, and gases spread to fill available space.",["ice → solid","water → liquid","water vapour → gas"],["Sort three examples into states of matter.","Describe what happens when ice melts."],"Explain one change of state using heating or cooling."),
  "Living and Non-Living Things":L("Distinguish living things from non-living things.","Living things carry out life processes such as growth, nutrition, respiration, response and reproduction. Non-living things do not carry out these processes independently.",["plant → living","stone → non-living"],["Classify five objects.","State one life process."],"Explain why a moving toy is still non-living."),
  "Plants and Their Parts":L("Identify basic plant parts and their functions.","Roots anchor and absorb water, stems support and transport, leaves make food, and flowers help many plants reproduce.",["root → absorption","stem → support and transport","leaf → photosynthesis"],["Label a plant diagram.","State one job of the roots."],"Explain what may happen if roots cannot absorb water."),
  "Animals and Habitats":L("Relate animals to places where they can live and find resources.","A habitat provides food, water, shelter and suitable conditions. Animals have features and behaviours that help them survive in their habitats.",["fish → aquatic habitat","camel → dry habitat"],["Match two animals to habitats.","Name one resource an animal needs."],"Explain one adaptation that helps an animal survive."),
  "Human Body":L("Identify major body organs and their basic functions.","Body systems work together. The heart pumps blood, lungs help with gas exchange, the digestive system processes food and the brain coordinates many activities.",["heart → pumps blood","lungs → gas exchange","stomach → digestion"],["Match two organs with their jobs.","Explain why breathing is necessary."],"Describe how two body systems work together."),
  "Energy":L("Recognise sources and uses of energy.","Energy enables movement, heating, lighting and other changes. Common sources include food, sunlight, fuels and batteries.",["food → body movement","battery → electrical device"],["Name three energy sources.","Describe one energy transfer."],"Explain why saving energy can be useful."),
  "Light and Sound":L("Describe how light and sound help us sense the world.","Light allows us to see objects, while sound is produced by vibrations and travels through a medium. Some sources make light or sound naturally and others are made by people.",["sun → light","vibrating string → sound"],["Name one light source.","Name one sound source."],"Explain why you cannot hear a sound without a vibrating source."),
  "Weather and Environment":L("Observe weather and explain how people affect their environment.","Weather includes conditions such as temperature, rainfall, wind and cloud cover. People can protect the environment by reducing waste, avoiding pollution and conserving resources.",["rainfall → amount of rain","wind → moving air"],["Describe today's weather.","Name one way to reduce litter."],"Suggest two actions that can protect a local environment.")
});

add("Social Studies",{
  "Family Unit":L("Explain the family as a social unit and recognise family responsibilities.","A family is a group of people connected by relationships and care. Families can have different structures, and members often share responsibilities such as care, support and cooperation.",["Parents and children may form a family.","Extended families can include grandparents and other relatives."],["Name two family responsibilities.","Give one way family members help one another."],"Explain why respect is important in a family."),
  "Community":L("Understand what a community is and how people contribute to it.","A community is a group of people who live, work or interact in a shared area. Schools, health centres, markets and places of worship can serve community needs.",["school → education","clinic → health care"],["Name two community services.","State one way to keep a community clean."],"Describe one problem in a community and a peaceful solution."),
  "Culture and Festivals":L("Recognise culture as shared ways of life and explain why festivals matter.","Culture includes language, food, clothing, music, beliefs, arts and customs. Festivals can preserve heritage and bring communities together.",["traditional food can reflect culture","festivals can celebrate history or harvests"],["Name one cultural practice.","Explain one reason people celebrate festivals."],"Compare two cultural practices respectfully."),
  "Family Responsibilities":L("Identify responsibilities that help a family function well.","Family members can contribute through care, communication, chores, financial support, education and emotional encouragement. Responsibilities should be shared appropriately.",["children can help with safe chores","adults provide guidance and care"],["Name one safe chore for a child.","Explain why sharing duties helps."],"Create a simple family responsibility chart."),
  "Occupations":L("Identify occupations and the services they provide.","An occupation is work that a person does. Different occupations meet needs in health, education, transport, farming, business and many other areas.",["teacher → education","nurse → health care"],["Match two occupations to services.","Name an occupation in your community."],"Explain how two different occupations depend on one another."),
  "Transportation":L("Describe ways people and goods move from one place to another.","Transportation can be by road, rail, water or air. The best method depends on distance, cost, safety and the type of goods or passengers involved.",["bus → road","boat → water","aircraft → air"],["Name one land and one water transport method.","State one safety rule."],"Compare two transport methods."),
  "Communication":L("Explain how people send and receive information.","Communication can be spoken, written, visual or digital. Clear communication uses suitable language and considers the person receiving the message.",["letter → written communication","phone call → spoken communication"],["Name two communication methods.","Write a clear short message."],"Explain why respectful digital communication matters."),
  "National Identity":L("Understand symbols and shared values that can help build national identity.","National identity can be expressed through shared history, civic values, symbols, languages and a sense of belonging. Respect for diversity is important in a plural society.",["national flag → symbol","national anthem → shared civic expression"],["Name one national symbol.","State one value that supports unity."],"Explain how respecting differences can strengthen a country.")
});

add("Civic Education",{
  "Rules and Regulations":L("Explain why rules are made and why lawful rules should be followed.","Rules provide guidance for behaviour and help people live, learn and work together safely. Regulations are formal rules created by an authority.",["school rules support order","traffic rules help road users stay safe"],["Give two examples of rules.","Explain one reason for obeying traffic rules."],"Describe what could happen if an important safety rule were ignored."),
  "Rights and Responsibilities":L("Distinguish rights from responsibilities.","Rights are freedoms or protections people are entitled to, while responsibilities are duties we should carry out. Rights and responsibilities work together in a community.",["right → access to lawful protection","responsibility → respect others' rights"],["Name one right and one responsibility.","Explain why responsibilities matter."],"Give an example of balancing a right with a responsibility."),
  "Good Citizenship":L("Identify behaviours that support responsible citizenship.","Good citizenship includes obeying lawful rules, respecting others, protecting public property, helping the community and participating peacefully in civic life.",["helping keep a public place clean","respecting another person's lawful rights"],["Name two responsible actions.","Give one example of community service."],"Plan one small civic action a learner can take."),
  "Honesty and Integrity":L("Understand honesty and integrity as trustworthy behaviour.","Honesty means telling the truth and avoiding deception. Integrity means doing what is right consistently, even when no one is watching.",["returning a lost item","admitting a mistake"],["Give one example of honest behaviour.","Explain why trust matters."],"Describe how integrity can affect a person's reputation."),
  "Cooperation and Respect":L("Use respectful cooperation to solve shared tasks.","Cooperation means working together toward a goal. Respect means recognising the dignity, rights and views of others while communicating appropriately.",["taking turns in a group","listening before responding"],["Name one way to cooperate.","Practise a respectful disagreement."],"Create three rules for a respectful group discussion."),
  "Democratic Values":L("Recognise values that support democratic participation.","Democratic values include participation, equality before the law, accountability, respect for rights and peaceful disagreement. These values help citizens take part responsibly.",["peaceful debate","fair participation"],["Name two democratic values.","Explain why peaceful disagreement is useful."],"Describe how accountability supports public trust."),
  "Human Rights":L("Understand that human rights protect the dignity of people.","Human rights are basic rights and freedoms recognised as belonging to people. They include protections related to dignity, equality and freedom, subject to lawful limits in particular systems.",["right to life","freedom from discrimination"],["Name one human right.","Explain why rights should be respected."],"Give one example of how a person can respect another person's rights."),
  "Peace and National Unity":L("Explain peaceful ways people can live and work together despite differences.","Peace involves resolving disagreements without violence. National unity is strengthened when people respect differences, cooperate and use lawful, peaceful ways to solve conflicts.",["dialogue can help resolve disagreements","tolerance can reduce unnecessary conflict"],["Name one peaceful conflict-resolution method.","Give one example of tolerance."],"Write three steps for resolving a disagreement peacefully.")
});

add("ICT",{
  "Output Devices and the Monitor":L("Identify output devices and explain what a monitor does.","An output device presents information from a computer to the user. A monitor displays text, pictures, video and other visual information.",["monitor → displays visual output","speaker → produces sound output"],["Name two output devices.","State one thing you can see on a monitor."],"Explain the difference between an input and output device."),
  "Input Devices and the Keyboard":L("Identify input devices and explain how a keyboard is used.","Input devices send data or commands to a computer. A keyboard lets a user type letters, numbers and commands.",["keyboard → typing","mouse → pointing and selecting"],["Name two input devices.","Type your name using a keyboard."],"Explain one difference between a keyboard and a monitor."),
  "Parts of a Computer":L("Recognise common computer components and their jobs.","A computer system contains components that help it receive input, process data, store information and produce output.",["CPU → processing","monitor → visual output","keyboard → input"],["Match three parts with their functions.","Identify one storage device."],"Explain how input, processing and output work together."),
  "Files and Folders":L("Organise digital information using files and folders.","A file stores information such as a document or picture. A folder helps group related files so they are easier to find and manage.",["Schoolwork folder → contains lesson files","photo.jpg → image file"],["Create a folder named Schoolwork.","Explain why clear file names help."],"Design a simple folder structure for a learner."),
  "Word Processing":L("Create and edit a simple document.","Word-processing software allows users to type, edit, format and save documents. Common tools include bold, alignment, font size and spell checking.",["type a paragraph","make a heading bold"],["Write a short paragraph.","Change a heading to bold."],"Format a one-page class note with a heading and two paragraphs."),
  "Internet Basics":L("Understand basic uses of the internet and safe browsing.","The internet connects computers and services so people can communicate, learn, search for information and use online tools. Users should check information and protect private details.",["search engine → finds information","website → online information or service"],["Name two uses of the internet.","Identify one piece of private information."],"Explain why not every online claim should be trusted immediately."),
  "Cyber Safety":L("Use safe habits when using connected devices and services.","Cyber safety includes strong passwords, privacy, careful clicking, software updates and telling a trusted adult about suspicious messages or harmful content.",["use a unique password","do not share a password publicly"],["Name two cyber-safety rules.","Explain why suspicious links should be avoided."],"Create a five-rule cyber-safety checklist."),
  "Digital Citizenship":L("Use technology responsibly and respectfully.","Digital citizenship means behaving responsibly online, respecting others, protecting information and understanding that online actions can have consequences.",["crediting another person's work","communicating respectfully"],["Give one example of respectful online behaviour.","Explain why copying work without credit is a problem."],"Write three rules for responsible digital citizenship.")
});

add("Basic Technology",{
  "Workshop Safety":L("Follow safe practices when working with tools and materials.","Workshop safety reduces injury. Keep tools in good condition, wear suitable protective equipment, follow instructions and keep the workspace orderly.",["wear eye protection when required","keep sharp tools handled safely"],["Name two safety rules.","Explain why tools should be checked before use."],"Create a short workshop safety poster."),
  "Hand Tools":L("Identify common hand tools and their uses.","Hand tools are operated manually for tasks such as cutting, fastening, measuring or shaping. The correct tool should be chosen for the job.",["hammer → driving nails","screwdriver → turning screws"],["Match two tools with uses.","Name a tool used for measuring."],"Explain why using the wrong tool can be unsafe or ineffective."),
  "Drawing Instruments and Lines":L("Use common technical drawing instruments and line types.","Technical drawing uses instruments such as rulers, set squares and compasses to produce accurate shapes and lines. Different line types communicate different information.",["ruler → straight measurement","compass → circles"],["Draw a straight line with a ruler.","Identify a curved line."],"Create a neat geometric drawing using two instruments."),
  "Wood":L("Describe wood as a useful natural material and recognise basic properties.","Wood comes from trees and can be cut, shaped, joined and finished for many products. Different woods have different strength, grain and durability.",["wood can be used for furniture","grain is the visible pattern in wood"],["Name two uses of wood.","State one property of wood."],"Explain why wood needs suitable finishing for some uses."),
  "Metals":L("Recognise metals as engineering materials and compare basic properties.","Metals are generally strong and can conduct heat or electricity. Different metals have different properties and are selected according to the job.",["copper → good electrical conductor","steel → strong engineering material"],["Name two metals.","Give one use of copper."],"Explain why different metals are chosen for different products.")
});

add("Agricultural Science",{
  "Crops":L("Identify crops and explain why they are grown.","Crops are plants cultivated for food, fibre, animal feed, medicine or other useful products. Farmers choose crops according to climate, soil and purpose.",["maize → food","cotton → fibre"],["Name three crops.","State one use of a crop."],"Explain one factor that affects crop choice."),
  "Soil":L("Describe soil and its importance to plant growth.","Soil supports plants and can contain minerals, air, water and organic matter. Soil properties affect drainage, root growth and nutrient availability.",["loamy soil can support many crops","organic matter improves soil structure"],["Name one soil component.","Explain why plants need soil."],"Describe one way farmers can protect soil."),
  "Farm Tools":L("Identify common farm tools and their uses.","Farm tools help with tasks such as digging, planting, weeding and harvesting. Using the correct tool makes work safer and more efficient.",["hoe → weeding and soil work","cutlass → clearing vegetation"],["Match two tools with uses.","State one tool-safety rule."],"Explain why tools should be cleaned and stored properly."),
  "Livestock":L("Recognise common farm animals and basic care needs.","Livestock are domesticated animals kept for useful products or services. They need suitable feed, water, shelter, hygiene and health care.",["cattle → milk or meat","poultry → eggs or meat"],["Name two livestock animals.","State two care needs."],"Explain why clean water matters for livestock."),
  "Farm Safety":L("Apply safety rules when working around farms and tools.","Farm safety includes careful tool handling, protective clothing, safe chemical practices and awareness of animals, machinery and uneven ground.",["store tools safely","follow instructions for farm chemicals"],["Name two farm hazards.","Give one prevention method."],"Create a five-point farm safety checklist."),
  "Food Production":L("Explain the basic stages involved in producing food.","Food production can involve preparing land, planting, caring for crops or animals, harvesting, processing, storage and distribution.",["plant → care → harvest","milk → collection → processing"],["Put three crop-production stages in order.","Name one storage method."],"Explain why proper storage reduces food waste.")
});

add("Physical and Health Education",{
  "Personal Hygiene":L("Practise habits that help keep the body clean and healthy.","Personal hygiene includes bathing, brushing teeth, washing hands, wearing clean clothes and caring for the body appropriately.",["brush teeth twice daily","wash hands with soap"],["Name three hygiene habits.","Explain why handwashing matters."],"Create a morning hygiene checklist."),
  "Nutrition":L("Understand why the body needs a balanced diet.","A balanced diet provides different nutrients needed for energy, growth, repair and healthy body functions. Variety and suitable portions matter.",["protein supports growth and repair","carbohydrates provide energy"],["Name two nutrient-rich foods.","Explain why water is important."],"Plan a simple balanced meal."),
  "Exercise":L("Explain how regular physical activity supports health.","Exercise helps develop fitness, strength, coordination and wellbeing. Activities should be appropriate to age and performed safely.",["walking","running","stretching"],["Name two safe activities.","Explain one benefit of exercise."],"Plan a short age-appropriate movement routine."),
  "Safety Rules":L("Recognise rules that reduce everyday risks.","Safety rules help people avoid preventable injuries at home, school, on roads and during play. Stop, look, listen and follow trusted instructions when appropriate.",["look both ways before crossing","do not play with dangerous objects"],["Name two safety rules.","Explain one road-safety habit."],"Create a safety poster for a classroom."),
  "Games and Movement":L("Develop coordination and teamwork through safe movement games.","Movement games can build balance, coordination, speed, agility and cooperation. Learners should warm up and follow fair-play rules.",["relay games","ball passing","balance activities"],["Name one teamwork game.","State one fair-play rule."],"Design a simple classroom movement game.")
});

add("JSS Mathematics",{
  "Simple Linear Equations":L("Solve simple linear equations by keeping both sides balanced.","An equation states that two expressions are equal. Use inverse operations to isolate the unknown while doing the same operation to both sides.",["2x + 5 = 15 → 2x = 10 → x = 5"],["Solve x + 7 = 12.","Check your answer by substitution."],"Write a linear equation whose solution is x = 8."),
  "Fractions, Decimals and Percentages":L("Convert and calculate among fractions, decimals and percentages.","Fractions, decimals and percentages are different ways of describing quantities. For example, 1/2 = 0.5 = 50%.",["1/4 = 0.25 = 25%","3/5 = 0.6 = 60%"],["Convert 3/4 to a percentage.","Find 20% of 150."],"Explain why 0.25 and 25% represent the same proportion."),
  "Angles and Polygon Properties":L("Use angle facts and polygon properties to solve geometry problems.","Angles can be classified by size. A polygon is a closed shape made from straight line segments. The sum of interior angles of an n-sided polygon is (n−2)×180°.",["triangle sum = 180°","quadrilateral sum = 360°"],["Find a missing angle in a triangle.","State the number of sides in a pentagon."],"Derive the interior-angle sum of a hexagon."),
  "Simultaneous Linear Equations":L("Solve two linear equations together to find two unknowns.","Simultaneous equations share unknowns. Elimination or substitution can remove one unknown, allowing the other to be found.",["x+y=9 and x−y=1 → 2x=10 → x=5, y=4"],["Solve x+y=10 and x−y=2.","Check both equations."],"Create two equations with a chosen solution pair."),
  "Statistics":L("Summarise and interpret numerical data.","Statistics helps us collect, organise and interpret data. Measures such as mean, median, mode and range describe different features of a data set.",["2,4,6 → mean = 4","range = highest − lowest"],["Find the mean of 3, 5 and 7.","Find the range of 2, 8, 4."],"Explain when the median may be useful.")
});
add("JSS English",{
  "Conjunctions":L("Use conjunctions to connect words and ideas.","Conjunctions join words, phrases or clauses. Words such as and, but, because, although and so show different relationships between ideas.",["I stayed home because it rained.","Kemi wanted to go, but she was busy."],["Choose a conjunction for a contrast sentence.","Join two short sentences with because."],"Write three sentences using different conjunctions."),
  "Figures of Speech":L("Recognise common figures of speech and explain their effect.","Figures of speech use language creatively. A simile compares using like or as; a metaphor makes a direct comparison; personification gives human qualities to non-human things.",["as brave as a lion → simile","The wind whispered → personification"],["Identify the figure in a sentence.","Create one simile."],"Explain why a writer might use personification."),
  "Direct and Indirect Speech":L("Change speech between direct and reported forms.","Direct speech gives a speaker's exact words in quotation marks. Indirect speech reports the meaning without quoting the exact words and may require changes in pronouns and tense.",["Ada said, 'I am tired.' → Ada said that she was tired."],["Convert one direct sentence to reported speech.","Check pronouns and tense."],"Report a two-sentence conversation accurately."),
  "Active and Passive Voice":L("Distinguish active and passive sentence structures.","In active voice, the subject performs the action. In passive voice, the receiver of the action is placed in the subject position and the verb uses a form of be plus a past participle.",["The boy kicked the ball. → The ball was kicked by the boy."],["Change one active sentence to passive.","Identify the doer and receiver."],"Explain when passive voice can be useful."),
  "Essay Writing":L("Plan and write a clear, organised essay.","An essay needs a clear purpose, logical paragraphs, relevant details and accurate language. Planning before writing helps ideas stay focused.",["introduction → body paragraphs → conclusion"],["Write an outline for a short essay.","Add a topic sentence to one paragraph."],"Edit your essay for grammar, punctuation and organisation.")
});
add("JSS Basic Science",{
  "Energy":L("Describe common forms and transfers of energy.","Energy can be stored and transferred. Chemical, electrical, thermal, light, sound and kinetic energy can change from one form to another.",["battery: chemical → electrical","moving object: kinetic energy"],["Name three forms of energy.","Describe one energy transfer."],"Trace the energy changes in a simple device."),
  "Digestive System":L("Describe how the digestive system processes food.","Digestion breaks food into smaller substances that can be absorbed. The mouth, oesophagus, stomach, small intestine, large intestine and accessory organs each have roles.",["mouth → chewing and saliva","small intestine → major nutrient absorption"],["Put digestive organs in order.","State one function of the stomach."],"Explain why absorption is important."),
  "Living and Non-Living Things":L("Use life processes to distinguish living from non-living things.","Living organisms carry out processes such as nutrition, respiration, growth, excretion, response and reproduction. Non-living objects do not carry out these processes as organisms do.",["plant → living","rock → non-living"],["List three life processes.","Classify two examples."],"Explain why fire is not classified as a living organism."),
  "Ecosystem":L("Explain how organisms interact with each other and their environment.","An ecosystem includes living organisms and non-living factors interacting in an area. Food chains show energy flow from producers to consumers and decomposers.",["grass → grasshopper → frog","sunlight supports producers"],["Identify a producer in a food chain.","Name one decomposer."],"Build a four-level food chain."),
  "Force and Friction":L("Explain how forces affect motion and how friction can help or hinder movement.","A force is a push or pull. Friction opposes relative motion between surfaces. It can provide grip, but it can also cause wear and energy loss.",["brakes use friction","shoe soles need friction for grip"],["Give one useful effect of friction.","Name one force that changes motion."],"Explain how lubrication changes friction.")
});
add("JSS Computer Studies / ICT",{
  "CPU":L("Explain the CPU as a central processing component.","The central processing unit executes instructions and coordinates processing. The arithmetic logic unit performs calculations and logical comparisons, while the control unit directs operations.",["ALU → arithmetic and logic","control unit → directs processing"],["State the role of the ALU.","Name one other CPU component."],"Explain why the CPU is often described as a processing centre."),
  "Input and Output Devices":L("Distinguish devices that send data to a computer from devices that present results.","Input devices provide data or commands. Output devices present processed information to the user.",["keyboard → input","monitor → output","speaker → output"],["Classify three devices.","Explain one difference between input and output."],"Describe an input-process-output example."),
  "Software":L("Distinguish software from hardware and identify common software types.","Software consists of instructions and programs. System software supports computer operation, while application software helps users perform tasks.",["operating system → system software","word processor → application"],["Define software.","Give one example of each type."],"Explain how software and hardware work together."),
  "Internet Safety and Cyber Ethics":L("Use the internet safely and behave responsibly online.","Cyber ethics covers responsible online behaviour, while safety includes protecting passwords, privacy and devices and avoiding suspicious links or harmful content.",["do not share passwords","respect other people's privacy"],["List two safe habits.","Explain why phishing messages are risky."],"Create a five-rule cyber-ethics code."),
  "Word Processing":L("Use word-processing tools to create a well-formatted document.","Word processors let users enter, edit, format, save and print or share documents. Formatting improves readability when used appropriately.",["bold a heading","align a paragraph"],["Create a heading and paragraph.","Use a shortcut to copy and paste text."],"Format a short report with a heading and numbered list.")
});
add("JSS Basic Technology",{
  "First Aid":L("Recognise basic first-aid actions and the purpose of common supplies.","First aid is immediate care given to an injured or suddenly ill person before professional medical help is available. Supplies such as clean dressings and antiseptic may support basic wound care when used appropriately.",["bandage → helps cover a wound","antiseptic → helps clean suitable minor wounds"],["Name two first-aid items.","State one reason for seeking adult or medical help."],"Describe safe first steps for a minor cut while avoiding unsafe treatment."),
  "Workshop Safety and Hand Tools":L("Use workshop tools safely and responsibly.","Safe workshop practice includes suitable protective equipment, correct tool selection, careful handling, good housekeeping and following instructions.",["hammer → nails","screwdriver → screws"],["Name two safety rules.","Match two tools to jobs."],"Explain why a damaged tool should not be used."),
  "Drawing Instruments and Lines":L("Use technical drawing tools to create accurate lines and shapes.","Rulers, set squares, compasses and pencils help produce accurate drawings. Different line conventions can communicate edges, centres or construction information.",["ruler → straight lines","compass → circles"],["Draw a perpendicular line.","Name two instruments."],"Create a neat labelled technical sketch."),
  "Wood":L("Describe wood properties, uses and basic working processes.","Wood is a natural material with grain, strength and moisture characteristics. It can be cut, shaped, joined and finished to make products.",["softwood → many construction uses","hardwood → furniture and durable products"],["Name two wood products.","State one wood property."],"Explain why wood grain can matter when working with wood."),
  "Metals":L("Compare common metals and explain why they are selected for particular uses.","Metals differ in strength, conductivity, hardness, corrosion resistance and workability. These properties influence their engineering uses.",["copper → electrical wiring","steel → structures and tools"],["Name two metals.","Give one use of steel."],"Explain why copper is useful in electrical work.")
});
add("National Values Education",{
  "National Consciousness":L("Explain how awareness of shared civic identity can support responsible citizenship.","National consciousness involves understanding one's civic community, history, responsibilities and shared institutions while recognising diversity.",["respecting national symbols","participating peacefully in community life"],["Name one civic responsibility.","Explain one way to support unity."],"Describe how young people can contribute positively to society."),
  "Integrity":L("Apply honesty and consistency to everyday decisions.","Integrity means acting according to sound principles and being trustworthy. It includes honesty, accountability and doing what is right even without supervision.",["admitting a mistake","returning property that is not yours"],["Give one example of integrity.","Explain why trust matters."],"Describe how integrity can influence leadership."),
  "Human Rights and Duties":L("Understand the relationship between rights and civic duties.","Rights protect human dignity and freedom, while duties describe responsibilities toward other people and society. Respecting others' rights is part of responsible citizenship.",["respect for lawful equality","duty to obey lawful rules"],["Name one right and one duty.","Explain why rights need responsibilities."],"Give an example of balancing personal freedom with another person's rights."),
  "Cultism and Drug Abuse":L("Recognise risks and prevention strategies related to harmful group pressure and drug misuse.","Cultism can involve secretive groups associated with harmful or unlawful activities. Drug misuse can damage health, learning, relationships and safety. Prevention includes informed choices, supportive relationships and seeking trusted help.",["refusing unsafe peer pressure","talking to a trusted adult about risky situations"],["Name one risk of drug misuse.","State one safe response to peer pressure."],"Create a support plan for a learner facing harmful peer pressure."),
  "Peace and Conflict Resolution":L("Use peaceful strategies to manage disagreement.","Conflict can arise from different needs, opinions or misunderstandings. Peaceful resolution may involve listening, negotiation, mediation, compromise and respect.",["listen before responding","use a trusted mediator when needed"],["Name two peaceful strategies.","Write one respectful response to disagreement."],"Create a five-step conflict-resolution process.")
});

add("SSS Mathematics",{
  "Indices and Logarithms":L("Apply laws of indices and basic logarithm relationships.","Indices describe repeated multiplication. Logarithms are inverse operations to exponentiation: if a^x=b, then log_a(b)=x.",["a^m × a^n = a^(m+n)","log_10(1000)=3"],["Simplify 2^3 × 2^2.","Evaluate log_10(100)."],"Explain how logarithms undo powers."),
  "Arithmetic and Geometric Progressions":L("Identify and use patterns in arithmetic and geometric sequences.","An arithmetic progression has a constant difference. A geometric progression has a constant ratio. Their nth-term and sum formulas help solve sequence problems.",["AP: 2,5,8,11 → d=3","GP: 3,6,12,24 → r=2"],["Find the next term of an AP.","Find the common ratio of a GP."],"Derive an nth-term expression for a simple sequence."),
  "Matrices and Determinants":L("Perform basic matrix operations and calculate determinants.","Matrices organise numbers in rows and columns. Addition requires matching dimensions, multiplication follows row-by-column rules, and a determinant gives a scalar value for a square matrix.",["For [[a,b],[c,d]], det = ad − bc"],["Find the determinant of a 2×2 matrix.","State when two matrices can be added."],"Explain how a determinant can indicate whether a 2×2 matrix has an inverse."),
  "Circle Geometry":L("Apply key theorems involving angles and circles.","Circle geometry links angles at the centre and circumference, chords, tangents and cyclic quadrilaterals. Correct diagrams and theorem selection are essential.",["angle at centre is twice angle at circumference on same arc","tangent is perpendicular to radius at point of contact"],["Identify a radius and chord.","Use one circle theorem in a simple problem."],"Explain one theorem using a labelled diagram."),
  "Probability":L("Calculate and interpret probabilities of events.","Probability measures how likely an event is. For equally likely outcomes, probability = favourable outcomes ÷ total outcomes, with values from 0 to 1.",["P(head on fair coin)=1/2","P(rolling 6)=1/6"],["Find P(even number) on a fair die.","State the probability of an impossible event."],"Explain why probabilities of all outcomes in a sample space add to 1.")
});
add("SSS Physics",{
  "Projectile Motion":L("Analyse the motion of an object launched through the air.","Projectile motion combines horizontal motion with vertical motion under gravity, ignoring air resistance in the ideal model. Resolve the initial velocity into components when needed.",["horizontal component remains constant in the ideal model","vertical velocity changes due to gravity"],["Identify horizontal and vertical components.","State the effect of gravity."],"Explain why the path is curved even when horizontal speed is constant."),
  "Simple Harmonic Motion":L("Describe oscillatory motion where restoring force is proportional to displacement.","In simple harmonic motion, the restoring force acts toward equilibrium and is proportional to displacement. Period and frequency describe the timing of oscillation.",["mass-spring system","small-angle pendulum approximation"],["Define amplitude.","Relate frequency and period."],"Explain what happens to velocity at equilibrium in ideal SHM."),
  "Waves":L("Describe wave properties and distinguish types of waves.","A wave transfers energy without transporting matter overall. Important properties include wavelength, frequency, amplitude and speed. Mechanical waves require a medium; electromagnetic waves can travel through vacuum.",["sound → mechanical","light → electromagnetic"],["Define wavelength.","Name one mechanical and one electromagnetic wave."],"Use v=fλ in a simple calculation."),
  "Electromagnetic Induction":L("Explain how changing magnetic flux can induce an emf.","Electromagnetic induction occurs when magnetic flux through a conductor or coil changes, producing an induced emf. Generators use this principle to convert mechanical energy into electrical energy.",["moving a magnet through a coil can induce voltage","generators use induction"],["State what must change to induce emf.","Name one application."],"Explain how a simple generator produces electrical output."),
  "Radioactivity and Half-Life":L("Understand radioactive decay and calculate simple half-life changes.","Radioactive nuclei can decay spontaneously and emit radiation. Half-life is the time required for half of a sample's radioactive nuclei to decay.",["100 units → 50 after one half-life → 25 after two"],["Find the remaining amount after two half-lives.","Name one type of nuclear radiation."],"Explain why radioactive activity decreases over time but does not suddenly become zero." )
});
add("SSS Chemistry",{
  "Stoichiometry and Limiting Reactants":L("Use balanced equations to calculate reacting quantities and identify the limiting reactant.","Stoichiometry relates amounts of substances using mole ratios from a balanced equation. The limiting reactant is consumed first and determines the maximum amount of product.",["2H₂ + O₂ → 2H₂O gives a 2:1 mole ratio for H₂:O₂"],["Balance a simple chemical equation.","Use a mole ratio to calculate product."],"Explain why excess reactant remains after a limiting reactant is used up."),
  "Equilibrium and Le Chatelier's Principle":L("Predict how an equilibrium system responds to changes.","At dynamic equilibrium, forward and reverse reaction rates are equal. Le Chatelier's principle says a system shifts in a way that tends to oppose an imposed change in concentration, pressure or temperature.",["adding a reactant can shift equilibrium toward products in a suitable system","temperature effects depend on whether the forward reaction is endothermic or exothermic"],["Define dynamic equilibrium.","Predict a concentration change qualitatively."],"Explain why a catalyst changes rate but not the equilibrium position."),
  "Electrochemistry":L("Relate chemical reactions to electrical energy and electrode processes.","Electrochemistry studies redox reactions involving electron transfer. Galvanic cells generate electrical energy from spontaneous reactions, while electrolysis uses electrical energy to drive non-spontaneous reactions.",["oxidation → loss of electrons","reduction → gain of electrons"],["Define oxidation.","Identify anode and cathode in a basic cell description."],"Explain how electron flow is related to electrical current in a cell."),
  "Rates of Reaction and Collision Theory":L("Explain why reaction rates change with conditions.","Collision theory states that particles must collide with suitable energy and orientation for a reaction to occur. Concentration, temperature, surface area and catalysts can affect collision frequency or energy.",["higher temperature generally increases successful collisions","powdered solid has greater surface area than a lump"],["Name two factors affecting rate.","Explain why a catalyst speeds a reaction."],"Describe how a concentration change can affect collision frequency."),
  "Organic Chemistry":L("Recognise carbon compounds and common organic families.","Organic chemistry studies carbon-containing compounds. Homologous series share functional patterns and show gradual changes in physical properties as chain length increases.",["alkanes → single C–C bonds","alkenes → contain C=C"],["Name one hydrocarbon family.","Identify whether a simple formula represents an alkane or alkene."],"Explain why isomers can have the same molecular formula but different structures." )
});
add("SSS English",{
  "Argumentative Essay":L("Build a balanced argument supported by reasons and evidence.","An argumentative essay presents a clear position, develops reasons with evidence, considers relevant opposing views and reaches a reasoned conclusion.",["introduction → position","body → reasons and evidence","conclusion → synthesis"],["Write two reasons for a position.","Add one counterargument and response."],"Edit an argument for clarity, evidence and logical flow."),
  "Advanced Concord":L("Apply subject-verb agreement in complex sentences.","Concord means grammatical agreement. Pay attention to the true subject, intervening phrases, compound subjects and structures such as neither...nor.",["Neither the principal nor the teachers were present.","The list of items is on the desk."],["Choose the correct verb in a concord sentence.","Identify the grammatical subject."],"Write three complex sentences with correct concord."),
  "Subordinate Clauses":L("Identify and use clauses that depend on a main clause.","A subordinate clause cannot normally stand alone as a complete sentence. It can show time, reason, condition, contrast or other relationships.",["because she was tired","although it rained","when the bell rang"],["Underline the subordinate clause.","Join two ideas using although."],"Write a sentence containing two different subordinate clauses."),
  "Comprehension and Summary":L("Extract key ideas and write concise summaries.","Comprehension requires close reading and evidence. A summary selects the central points and expresses them briefly in your own words without unnecessary details.",["main idea → supporting points → concise summary"],["Identify the main idea of a passage.","Write a two-sentence summary."],"Reduce a paragraph to its essential information without changing its meaning."),
  "Register: Law and ICT":L("Recognise vocabulary and style appropriate to professional contexts.","Register is the language chosen for a particular field or situation. Legal and ICT contexts use specialised terms whose meanings depend on professional usage.",["law → affidavit, defendant, statute","ICT → network, algorithm, database"],["Match two terms to their fields.","Use one register word correctly in a sentence."],"Rewrite an informal sentence using an appropriate professional register.")
});
add("SSS Government",{
  "Federalism":L("Explain the constitutional division of powers in a federal system.","Federalism distributes constitutional powers between levels of government so that each has defined responsibilities. The exact division depends on the constitution of the country.",["federal level → national responsibilities","subnational level → constitutionally assigned responsibilities"],["Define federalism.","State one reason for dividing powers."],"Explain one advantage and one challenge of divided powers without ranking them."),
  "Public Corporations":L("Describe the purpose and characteristics of public corporations.","A public corporation is a government-established body created to provide particular services or manage public economic activities. Its structure and accountability depend on the legal framework that creates it.",["public transport or utilities may be organised through public bodies","public corporations can have boards and statutory duties"],["Define public corporation.","Name one possible public service role."],"Explain why accountability matters in a public corporation."),
  "Political Parties":L("Explain the roles political parties play in representative government.","Political parties organise political participation, develop programmes, nominate candidates and seek support through elections. Different parties may have different ideologies and policy proposals.",["candidate selection","policy platforms","voter mobilisation"],["Name two party functions.","Explain what a manifesto is."],"Compare two party functions without evaluating which is better."),
  "Electoral Systems":L("Understand common ways votes are translated into political representation.","Electoral systems set rules for casting votes and determining results. Examples include plurality/majority systems and proportional representation, each with different mechanics.",["first-past-the-post → candidate with the most votes in a constituency wins","proportional representation → seats are allocated using a proportional method"],["Define electoral system.","Describe one system's basic rule."],"Explain why electoral-system design can affect representation."),
  "Pre-Colonial Administration":L("Describe forms of political organisation in Nigerian societies before colonial rule.","Pre-colonial societies in the region had diverse systems of authority, including centralised kingdoms and emirates as well as more decentralised arrangements. Administration varied by society and period.",["centralised systems could have kings, chiefs and councils","some communities used councils, age grades or other institutions"],["Name one feature of a centralised system.","Explain why pre-colonial systems should not be treated as identical."],"Compare two broad forms of pre-colonial political organisation.")
});
add("SSS Biology",{
  "Cell Division":L("Explain mitosis and meiosis and their roles in organisms.","Mitosis produces genetically similar daughter cells for growth and repair. Meiosis produces sex cells with half the chromosome number and contributes to genetic variation.",["mitosis → growth and repair","meiosis → gamete formation"],["State one difference between mitosis and meiosis.","Explain why chromosome number is reduced in meiosis."],"Describe how crossing over can increase variation."),
  "Ecology and the Nitrogen Cycle":L("Explain ecosystem relationships and the movement of nitrogen through nature.","Nitrogen is essential for proteins and nucleic acids. In the nitrogen cycle, microorganisms help convert nitrogen between atmospheric, soil and biologically usable forms.",["nitrogen fixation","nitrification","denitrification"],["Name one nitrogen-cycle process.","Explain why plants need usable nitrogen."],"Trace nitrogen from the atmosphere to a plant and back."),
  "Plant Transport":L("Explain how water, minerals and sugars move through plants.","Xylem transports water and mineral ions mainly upward from roots. Phloem transports sugars and other organic substances from sources to sinks through translocation.",["xylem → water and minerals","phloem → sugars"],["State one xylem function.","State one phloem function."],"Explain how transpiration contributes to water movement."),
  "Nervous Coordination and Reflex Arc":L("Describe how the nervous system detects and responds to stimuli.","Receptors detect stimuli and nerve impulses travel through neurones. A reflex arc provides a rapid pathway involving a receptor, sensory neurone, relay neurone, motor neurone and effector.",["hot surface → receptor → spinal pathway → muscle response"],["Put the main reflex-arc components in order.","Define stimulus."],"Explain why reflex actions can be rapid."),
  "Evolution and Natural Selection":L("Explain how inherited variation and selection can change populations over generations.","Evolution describes changes in inherited characteristics of populations over generations. Natural selection occurs when heritable variation affects survival or reproduction, causing some traits to become more common over time.",["variation → different survival/reproduction outcomes","Darwin proposed natural selection as a mechanism of evolution"],["Define natural selection.","Give one example of inherited variation."],"Explain how environmental pressure can change the frequency of a trait in a population.")
});

// Friendly fallbacks for any topic that remains in a grouped curriculum.
function buildLesson(title,subject,level,index=0){
 const direct=(window.LESSON_CONTENT[`${level} ${subject}`]||{})[title] || (window.LESSON_CONTENT[subject]||{})[title];
 if(direct)return direct;
 return L(`Build a clear foundation in ${title}.`,`This ${subject} lesson introduces ${title}. Learn the key terms, connect the idea to an example, practise the skill step by step, and check your understanding before moving on.`,[`Key idea: ${title}.`,`Use a simple real-life example before attempting harder questions.`],[`Define or describe ${title} in your own words.`,`Create one example and explain why it fits the topic.`],`Teach the main idea of ${title} to another learner in three clear steps.`);
}
